export const GET_BOOKS_REQUEST="GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS="GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE="GET_BOOKS_FAILURE";

//edit
export const EDIT_BOOKS_REQUEST="GET_BOOKS_REQUEST";
export const EDIT_BOOKS_SUCCESS="GET_BOOKS_REQUEST";
export const EDIT_BOOKS_FAILURE="GET_BOOKS_REQUEST";